exports.main =  function(maxValue) {
    console.log(
        "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: \n" +
        "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... \n" +
        "By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.\n"
    );

    console.log("solution:");
    console.log("--------");

    let secondLastNo = 1;
    let lastNo = 1;

    let arrFibonacci = [lastNo];
    let sumOfEvenFib = 0;
    let boolExecuteLoop = true;

    while (boolExecuteLoop) {
        let tempValue = lastNo;
        lastNo += secondLastNo;
        secondLastNo = tempValue;

        if (lastNo <= maxValue) {
            arrFibonacci.push(lastNo);

            //uncomment for Fibonacci generation sequence
            //console.log(arrFibonacci);

            if (lastNo % 2 === 0) {
                sumOfEvenFib += lastNo;
            }
        } else {
            boolExecuteLoop = false;
        }
    }

    console.log("Fibonacci: \n" + arrFibonacci);
    console.log("\n sum of fibonacci even related is " + sumOfEvenFib + " whose Fibonacci sequence values does not exceed " + maxValue + " (Actual Fibonacci last value : " + arrFibonacci[arrFibonacci.length - 1] + ") ");
}
